import { settingsService } from "./settings";
import { SettingCategory, SettingType, SettingScope } from "@prisma/client";

interface DefaultSetting {
  key: string;
  name: string;
  nameAr: string;
  description: string;
  category: SettingCategory;
  type: SettingType;
  scope: SettingScope;
  value: string;
  sortOrder: number;
}

const defaultSettings: DefaultSetting[] = [
  // إعدادات عامة
  {
    key: "site_name",
    name: "Site Name",
    nameAr: "اسم الموقع",
    description: "اسم التطبيق الذي يظهر للمستخدمين",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "Alketan",
    sortOrder: 1,
  },
  {
    key: "site_description",
    name: "Site Description",
    nameAr: "وصف الموقع",
    description: "وصف مختصر للتطبيق",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "Hotel Booking Management System",
    sortOrder: 2,
  },
  {
    key: "supported_countries",
    name: "Supported Countries",
    nameAr: "الدول المدعومة",
    description: "قائمة الدول المدعومة مفصولة بفواصل",
    category: SettingCategory.GENERAL,
    type: SettingType.ARRAY,
    scope: SettingScope.GLOBAL,
    value: JSON.stringify(["SA", "AE", "EG", "US", "UK", "DE", "FR"]),
    sortOrder: 3,
  },
  {
    key: "default_currency",
    name: "Default Currency",
    nameAr: "العملة الافتراضية",
    description: "العملة الافتراضية للنظام",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "USD",
    sortOrder: 4,
  },
  {
    key: "default_language",
    name: "Default Language",
    nameAr: "اللغة الافتراضية",
    description: "اللغة الافتراضية للنظام",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "ar",
    sortOrder: 5,
  },

  // إعدادات النظام
  {
    key: "maintenance_mode",
    name: "Maintenance Mode",
    nameAr: "وضع الصيانة",
    description: "تفعيل وضع الصيانة لإيقاف الخدمة مؤقتاً",
    category: SettingCategory.SYSTEM,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "false",
    sortOrder: 1,
  },
  {
    key: "lockdown_mode",
    name: "Lockdown Mode",
    nameAr: "وضع الإغلاق",
    description: "تفعيل وضع الإغلاق الطارئ",
    category: SettingCategory.SYSTEM,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "false",
    sortOrder: 2,
  },
  {
    key: "max_login_attempts",
    name: "Max Login Attempts",
    nameAr: "الحد الأقصى لمحاولات تسجيل الدخول",
    description: "عدد المحاولات المسموح بها قبل قفل الحساب",
    category: SettingCategory.SYSTEM,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "5",
    sortOrder: 3,
  },
  {
    key: "session_timeout",
    name: "Session Timeout (minutes)",
    nameAr: "مهلة انتهاء الجلسة",
    description: "مهلة انتهاء الجلسة غير النشطة بالدقائق",
    category: SettingCategory.SYSTEM,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "30",
    sortOrder: 4,
  },
  {
    key: "password_expiry_days",
    name: "Password Expiry (days)",
    nameAr: "انتهاء صلاحية كلمة المرور",
    description: "عدد الأيام قبل طلب تغيير كلمة المرور",
    category: SettingCategory.SYSTEM,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "90",
    sortOrder: 5,
  },

  // إعدادات الحجوزات
  {
    key: "booking_max_nights",
    name: "Maximum Booking Nights",
    nameAr: "الحد الأقصى لعدد ليالي الحجز",
    description: "الحد الأقصى لعدد الليالي المسموح به في حجز واحد",
    category: SettingCategory.BOOKING,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "30",
    sortOrder: 1,
  },
  {
    key: "booking_min_nights",
    name: "Minimum Booking Nights",
    nameAr: "الحد الأدنى لعدد ليالي الحجز",
    description: "الحد الأدنى لعدد الليالي المسموح به في حجز واحد",
    category: SettingCategory.BOOKING,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "1",
    sortOrder: 2,
  },
  {
    key: "booking_max_guests",
    name: "Maximum Guests per Booking",
    nameAr: "الحد الأقصى للضيوف في الحجز",
    description: "الحد الأقصى لعدد الضيوف المسموح به في حجز واحد",
    category: SettingCategory.BOOKING,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "10",
    sortOrder: 3,
  },
  {
    key: "advance_booking_days",
    name: "Advance Booking Days",
    nameAr: "أيام الحجز المسبق",
    description: "الحد الأقصى لعدد الأيام للحجز المسبق",
    category: SettingCategory.BOOKING,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "365",
    sortOrder: 4,
  },
  {
    key: "cancel_booking_hours",
    name: "Cancel Booking Hours",
    nameAr: "ساعات إلغاء الحجز",
    description: "الحد الأدنى من الساعات قبل تسجيل الوصول للإلغاء بدون غرامة",
    category: SettingCategory.BOOKING,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "24",
    sortOrder: 5,
  },

  // إعدادات الأمان
  {
    key: "two_factor_required",
    name: "Two-Factor Authentication Required",
    nameAr: "المصادقة الثنائية مطلوبة",
    description: "طلب المصادقة الثنائية لجميع المستخدمين",
    category: SettingCategory.SECURITY,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "false",
    sortOrder: 1,
  },
  {
    key: "ip_whitelist",
    name: "IP Whitelist",
    nameAr: "قائمة IPs المسموحة",
    description: "قائمة عناوين IP المسموحة (JSON array)",
    category: SettingCategory.SECURITY,
    type: SettingType.ARRAY,
    scope: SettingScope.GLOBAL,
    value: JSON.stringify([]),
    sortOrder: 2,
  },
  {
    key: "rate_limit_requests",
    name: "Rate Limit (requests per minute)",
    nameAr: "حد معدل الطلبات",
    description: "الحد الأقصى للطلبات في الدقيقة",
    category: SettingCategory.SECURITY,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "60",
    sortOrder: 3,
  },

  // إعدادات الإشعارات
  {
    key: "email_notifications_enabled",
    name: "Email Notifications Enabled",
    nameAr: "تفعيل إشعارات البريد",
    description: "تفعيل إرسال إشعارات عبر البريد الإلكتروني",
    category: SettingCategory.NOTIFICATION,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "true",
    sortOrder: 1,
  },
  {
    key: "sms_notifications_enabled",
    name: "SMS Notifications Enabled",
    nameAr: "تفعيل إشعارات الرسائل القصيرة",
    description: "تفعيل إرسال إشعارات عبر الرسائل القصيرة",
    category: SettingCategory.NOTIFICATION,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "true",
    sortOrder: 2,
  },
  {
    key: "push_notifications_enabled",
    name: "Push Notifications Enabled",
    nameAr: "تفعيل الإشعارات الفورية",
    description: "تفعيل الإشعارات الفورية على الأجهزة",
    category: SettingCategory.NOTIFICATION,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "true",
    sortOrder: 3,
  },

  // إعدادات برنامج الولاء
  {
    key: "loyalty_points_booking",
    name: "Points per Booking",
    nameAr: "نقاط لكل حجز",
    description: "عدد النقاط المكتسبة لكل حجز",
    category: SettingCategory.LOYALTY,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "100",
    sortOrder: 1,
  },
  {
    key: "loyalty_points_rate",
    name: "Currency to Points Rate",
    nameAr: "سعر الصرف للنقاط",
    description: "عدد النقاط لكل وحدة عملة",
    category: SettingCategory.LOYALTY,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "10",
    sortOrder: 2,
  },
  {
    key: "loyalty_discount_percent",
    name: "Loyalty Discount Percent",
    nameAr: "نسبة خصم الولاء",
    description: "نسبة الخصم لأعضاء برنامج الولاء",
    category: SettingCategory.LOYALTY,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "5",
    sortOrder: 3,
  },

  // إعدادات التصدير
  {
    key: "export_date_format",
    name: "Export Date Format",
    nameAr: "شكل التاريخ في التصدير",
    description: "شكل التاريخ المستخدم في ملفات التصدير",
    category: SettingCategory.EXPORT,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "YYYY-MM-DD",
    sortOrder: 1,
  },
  {
    key: "export_max_records",
    name: "Export Max Records",
    nameAr: "الحد الأقصى للسجلات في التصدير",
    description: "الحد الأقصى لعدد السجلات المسموح به في التصدير",
    category: SettingCategory.EXPORT,
    type: SettingType.NUMBER,
    scope: SettingScope.GLOBAL,
    value: "10000",
    sortOrder: 2,
  },

  // إعدادات أوقات العمل
  {
    key: "default_checkin_time",
    name: "Default Check-in Time",
    nameAr: "وقت تسجيل الدخول الافتراضي",
    description: "وقت تسجيل الوصول الافتراضي للفنادق (صيغة 24 ساعة)",
    category: SettingCategory.HOTEL,
    type: SettingType.STRING,
    scope: SettingScope.HOTEL,
    value: "15:00",
    sortOrder: 1,
  },
  {
    key: "default_checkout_time",
    name: "Default Check-out Time",
    nameAr: "وقت تسجيل الخروج الافتراضي",
    description: "وقت تسجيل المغادرة الافتراضي للفنادق (صيغة 24 ساعة)",
    category: SettingCategory.HOTEL,
    type: SettingType.STRING,
    scope: SettingScope.HOTEL,
    value: "11:00",
    sortOrder: 2,
  },
  {
    key: "reception_working_hours_start",
    name: "Reception Working Hours Start",
    nameAr: "بداية ساعات عمل الاستقبال",
    description: "وقت بداية عمل الاستقبال (صيغة 24 ساعة)",
    category: SettingCategory.HOTEL,
    type: SettingType.STRING,
    scope: SettingScope.HOTEL,
    value: "00:00",
    sortOrder: 3,
  },
  {
    key: "reception_working_hours_end",
    name: "Reception Working Hours End",
    nameAr: "نهاية ساعات عمل الاستقبال",
    description: "وقت نهاية عمل الاستقبال (صيغة 24 ساعة)",
    category: SettingCategory.HOTEL,
    type: SettingType.STRING,
    scope: SettingScope.HOTEL,
    value: "23:59",
    sortOrder: 4,
  },
  {
    key: "reception_24_7",
    name: "Reception 24/7",
    nameAr: "استقبال على مدار الساعة",
    description: "هل الاستقبال يعمل على مدار الساعة",
    category: SettingCategory.HOTEL,
    type: SettingType.BOOLEAN,
    scope: SettingScope.HOTEL,
    value: "false",
    sortOrder: 5,
  },

  // إعدادات القفل والفتح المجدول
  {
    key: "scheduled_lock_enabled",
    name: "Scheduled Lock Enabled",
    nameAr: "تفعيل القفل المجدول",
    description: "تفعيل أو تعطيل القفل المجدول للتطبيق",
    category: SettingCategory.SYSTEM,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "false",
    sortOrder: 10,
  },
  {
    key: "scheduled_lock_start_time",
    name: "Scheduled Lock Start Time",
    nameAr: "وقت بدء القفل المجدول",
    description: "الوقت الذي يبدأ فيه قفل التطبيق (صيغة HH:mm)",
    category: SettingCategory.SYSTEM,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "22:00",
    sortOrder: 11,
  },
  {
    key: "scheduled_lock_end_time",
    name: "Scheduled Lock End Time",
    nameAr: "وقت انتهاء القفل المجدول",
    description: "الوقت الذي ينتهي فيه قفل التطبيق (صيغة HH:mm)",
    category: SettingCategory.SYSTEM,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "06:00",
    sortOrder: 12,
  },
  {
    key: "scheduled_lock_days",
    name: "Scheduled Lock Days",
    nameAr: "أيام القفل المجدول",
    description: "أيام الأسبوع التي يُطبَّق فيها القفل (JSON array: 0=الأحد, 6=السبت)",
    category: SettingCategory.SYSTEM,
    type: SettingType.ARRAY,
    scope: SettingScope.GLOBAL,
    value: JSON.stringify([0, 1, 2, 3, 4, 5, 6]), // كل الأيام
    sortOrder: 13,
  },
  {
    key: "lock_message",
    name: "Lock Message",
    nameAr: "رسالة القفل",
    description: "الرسالة التي تظهر للمستخدمين عند قفل التطبيق",
    category: SettingCategory.SYSTEM,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "التطبيق مغلق حالياً. يرجى المحاولة لاحقاً.",
    sortOrder: 14,
  },
  {
    key: "lock_message_ar",
    name: "Lock Message (Arabic)",
    nameAr: "رسالة القفل بالعربية",
    description: "الرسالة العربية التي تظهر للمستخدمين عند قفل التطبيق",
    category: SettingCategory.SYSTEM,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "التطبيق مغلق حالياً. يرجى المحاولة لاحقاً.",
    sortOrder: 15,
  },

  // إعدادات الشريط أو الرسالة المؤقتة
  {
    key: "announcement_banner_enabled",
    name: "Announcement Banner Enabled",
    nameAr: "تفعيل شريط الإعلانات",
    description: "تفعيل أو تعطيل شريط الإعلانات المؤقت",
    category: SettingCategory.GENERAL,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "false",
    sortOrder: 20,
  },
  {
    key: "announcement_banner_text",
    name: "Announcement Banner Text",
    nameAr: "نص شريط الإعلانات",
    description: "النص الذي يظهر في شريط الإعلانات",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "عروض خاصة لفصل الصيف! احجز الآن واحصل على خصم 20%",
    sortOrder: 21,
  },
  {
    key: "announcement_banner_text_ar",
    name: "Announcement Banner Text (Arabic)",
    nameAr: "نص شريط الإعلانات بالعربية",
    description: "النص العربي الذي يظهر في شريط الإعلانات",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "عروض خاصة لفصل الصيف! احجز الآن واحصل على خصم 20%",
    sortOrder: 22,
  },
  {
    key: "announcement_banner_color",
    name: "Announcement Banner Color",
    nameAr: "لون شريط الإعلانات",
    description: "لون خلفية شريط الإعلانات (hex code)",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "#FF6B6B",
    sortOrder: 23,
  },
  {
    key: "announcement_banner_text_color",
    name: "Announcement Banner Text Color",
    nameAr: "لون نص شريط الإعلانات",
    description: "لون نص شريط الإعلانات (hex code)",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "#FFFFFF",
    sortOrder: 24,
  },
  {
    key: "announcement_banner_link",
    name: "Announcement Banner Link",
    nameAr: "رابط شريط الإعلانات",
    description: "الرابط الذي ينتقل إليه المستخدم عند الضغط على الشريط (اختياري)",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "",
    sortOrder: 25,
  },
  {
    key: "announcement_banner_start_date",
    name: "Announcement Banner Start Date",
    nameAr: "تاريخ بدء شريط الإعلانات",
    description: "تاريخ بدء ظهور شريط الإعلانات (ISO 8601)",
    category: SettingCategory.GENERAL,
    type: SettingType.DATETIME,
    scope: SettingScope.GLOBAL,
    value: "",
    sortOrder: 26,
  },
  {
    key: "announcement_banner_end_date",
    name: "Announcement Banner End Date",
    nameAr: "تاريخ انتهاء شريط الإعلانات",
    description: "تاريخ انتهاء ظهور شريط الإعلانات (ISO 8601)",
    category: SettingCategory.GENERAL,
    type: SettingType.DATETIME,
    scope: SettingScope.GLOBAL,
    value: "",
    sortOrder: 27,
  },

  // إعدادات المظهر والثيم
  {
    key: "default_theme",
    name: "Default Theme",
    nameAr: "الثيم الافتراضي",
    description: "الثيم الافتراضي للتطبيق (light, dark, system)",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.USER,
    value: "system",
    sortOrder: 30,
  },
  {
    key: "primary_color",
    name: "Primary Color",
    nameAr: "اللون الأساسي",
    description: "اللون الأساسي للتطبيق (hex code)",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "#3B82F6",
    sortOrder: 31,
  },
  {
    key: "secondary_color",
    name: "Secondary Color",
    nameAr: "اللون الثانوي",
    description: "اللون الثانوي للتطبيق (hex code)",
    category: SettingCategory.GENERAL,
    type: SettingType.STRING,
    scope: SettingScope.GLOBAL,
    value: "#10B981",
    sortOrder: 32,
  },
  {
    key: "enable_dark_mode",
    name: "Enable Dark Mode",
    nameAr: "تفعيل الوضع الداكن",
    description: "هل يُسمَح للمستخدمين باستخدام الوضع الداكن",
    category: SettingCategory.GENERAL,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "true",
    sortOrder: 33,
  },

  // إعدادات اللغة والتوجيه
  {
    key: "supported_languages",
    name: "Supported Languages",
    nameAr: "اللغات المدعومة",
    description: "قائمة اللغات المدعومة في التطبيق (JSON array: ar, en, fr, etc.)",
    category: SettingCategory.GENERAL,
    type: SettingType.ARRAY,
    scope: SettingScope.GLOBAL,
    value: JSON.stringify(["ar", "en"]),
    sortOrder: 40,
  },
  {
    key: "force_rtl",
    name: "Force RTL",
    nameAr: "فرض اتجاه RTL",
    description: "فرض اتجاه الكتابة من اليمين لليسار",
    category: SettingCategory.GENERAL,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "true",
    sortOrder: 41,
  },
  {
    key: "show_language_selector",
    name: "Show Language Selector",
    nameAr: "إظهار منتقي اللغة",
    description: "إظهار قائمة اختيار اللغة للمستخدم",
    category: SettingCategory.GENERAL,
    type: SettingType.BOOLEAN,
    scope: SettingScope.GLOBAL,
    value: "true",
    sortOrder: 42,
  },

  // إعدادات الحجز الإضافية
  {
    key: "allow_same_day_booking",
    name: "Allow Same Day Booking",
    nameAr: "السماح بالحجز في نفس اليوم",
    description: "هل يُسمَح بالحجز في نفس يوم تسجيل الوصول",
    category: SettingCategory.BOOKING,
    type: SettingType.BOOLEAN,
    scope: SettingScope.HOTEL,
    value: "true",
    sortOrder: 10,
  },
  {
    key: "require_deposit",
    name: "Require Deposit",
    nameAr: "طلب دفعة مقدمة",
    description: "هل يُطلَب دفع مبلغ مقدم للحجز",
    category: SettingCategory.BOOKING,
    type: SettingType.BOOLEAN,
    scope: SettingScope.HOTEL,
    value: "false",
    sortOrder: 11,
  },
  {
    key: "deposit_percentage",
    name: "Deposit Percentage",
    nameAr: "نسبة الدفعة المقدمة",
    description: "نسبة المبلغ المطلوب كدفعة مقدمة (0-100)",
    category: SettingCategory.BOOKING,
    type: SettingType.NUMBER,
    scope: SettingScope.HOTEL,
    value: "20",
    sortOrder: 12,
  },
  {
    key: "allow_booking_modification",
    name: "Allow Booking Modification",
    nameAr: "السماح بتعديل الحجز",
    description: "هل يُسمَح بتعديل الحجز بعد التأكيد",
    category: SettingCategory.BOOKING,
    type: SettingType.BOOLEAN,
    scope: SettingScope.HOTEL,
    value: "true",
    sortOrder: 13,
  },
  {
    key: "booking_modification_hours",
    name: "Booking Modification Hours",
    nameAr: "ساعات تعديل الحجز",
    description: "عدد الساعات قبل تسجيل الوصول التي يمكن تعديل الحجز خلالها",
    category: SettingCategory.BOOKING,
    type: SettingType.NUMBER,
    scope: SettingScope.HOTEL,
    value: "48",
    sortOrder: 14,
  },
];

export async function seedDefaultSettings() {
  console.log("🌱 بدء إضافة الإعدادات الافتراضية...");

  const results = {
    created: 0,
    skipped: 0,
    errors: 0,
  };

  for (const setting of defaultSettings) {
    try {
      const existing = await settingsService.getSettingByKey(setting.key);

      if (existing) {
        console.log(`⏭️  تخطي: ${setting.key} (موجود)`);
        results.skipped++;
        continue;
      }

      await settingsService.createSetting(setting);
      console.log(`✅ إنشاء: ${setting.key}`);
      results.created++;
    } catch (error: any) {
      console.error(`❌ خطأ في ${setting.key}: ${error.message}`);
      results.errors++;
    }
  }

  console.log("\n📊 ملخص:");
  console.log(`   - تم إنشاء: ${results.created}`);
  console.log(`   - تم تخطي: ${results.skipped}`);
  console.log(`   - أخطاء: ${results.errors}`);

  return results;
}
